### ISSUE TITLE
Input link failed to display topic

### ISSUE THREAD

**Issue by victorGPT** [xavez/roam-research-macos-dark#1]
![image](https://user-images.githubusercontent.com/24761742/84568523-8d9ecd00-adb2-11ea-9a46-a058569bff49.png)

**Comment by xavez** [comment]
@victor-crypto whoops, looks like I completely missed this issue for more than a year... Notifications were off for some reason.

I'm not sure what you meant with the comment, can you elaborate? Even if you're not using the theme anymore I'd still like to understand what happened so that I can solve it. Thanks!
